server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tx-ssc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  #下划线转驼峰
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.goodcub.shishicai.entity

pagehelper:
    helperDialect: mysql                           #分页插件方言选择
    reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: true

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
