server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tx-ssc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.goodcub.shishicai.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
